CUDA_VISIBLE_DEVICES=1 accelerate launch --main_process_port 29504 scripts/train_mcts_mle.py \
--config config/svdd_aesthetic_mle.py \
--config.search.duplicate 2 \
--config.run_name search_amortize \
--config.train.learning_rate 3e-4 \
--config.train.total_batch_size 1 \
--config.train.gradient_steps_per_improve_step 500 \
--config.train.improve_steps 10 \
--config.sample.num_batches_per_epoch 1 \
--config.prompt_fn simple_animals \
--config.train.kl_coef 0.00 \
--config.train.type 'sft' \
--config.eval.num_images_per_prompt 8 \
--config.sample.num_prompts_per_batch 1 \
--config.tree_amortization 'dpo' \