CUDA_VISIBLE_DEVICES=4,5,6,7 accelerate launch --main_process_port 29501 scripts/sample.py \
--config config/svdd_aesthetic_mle.py \
--config.run_name pick_0.0005_4_0.9 \
--config.train.learning_rate 2e-3 \
--config.train.total_batch_size 64 \
--config.train.gradient_steps_per_improve_step 500 \
--config.train.improve_steps 1 \
--config.sample.num_batches_per_epoch 50 \
--config.prompt_fn hps_eval \
--config.train.kl_coef 0.01 \
--config.train.type 'energy_based_negative_gradient' \
--config.eval.num_images_per_prompt 8 \
--config.sample.num_prompts_per_batch 50 \
--config.sample.num_steps 50 \
--config.search.value_gradient \
--config.reward_fn PickScore \
--config.num_epochs 1 \
--config.multistep_mdp \
--noconfig.train.negative_gradient \
--config.search.importance_sampling \
--config.search.hill_climbing \
--config.buffer.per_prompt_filtering_flag \
--noconfig.buffer.per_prompt_select_flag \
--config.buffer.reward_filtering_criteria 0.0 \
--config.buffer.clip_score_filtering_criteria 0.0 \
--config.buffer.off_policy_subset_size 0 \
--config.save_freq 1000 \
--config.train.clip_range 0.0001 \
--config.search.duplicate 4 \
--config.search.gamma 0.90 \
--config.search.kl_lagrangian_coef 0.00005 \