accelerate launch --main_process_port 29501 scripts/train_mcts_mle.py \
--config config/svdd_aesthetic_mle.py \
--config.run_name comp_1improve_0 \
--config.reward_fn jpeg_compressibility \
--config.prompt_fn simple_animals \
--config.train.type 'energy_based_negative_gradient' \
--config.train.learning_rate 3e-4 \
--config.sample.num_steps 50 \
--config.num_epochs 10 \
--config.eval.eval_freq 1 \
--config.save_freq 2 \
--config.multistep_mdp \
--config.seed 0 \
--config.sample.num_prompts_per_batch 8 \
--config.sample.num_batches_per_epoch 8 \
--noconfig.search.value_gradient \
--config.search.kl_lagrangian_coef 0.005 \
--config.search.duplicate 20 \
--config.search.gamma 0.90 \
--config.search.importance_sampling \
--config.search.hill_climbing \
--config.train.improve_steps 1 \
--noconfig.train.negative_gradient \
--config.train.kl_coef 0.01 \
